FROM node:17-latest as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build


# Step 2
## base image for Step 2: Node 14-alpine(light weight)
# node예전버전 사용시 graphql 안됌 
FROM node:17-alpine
WORKDIR /app
## Step 1의 builder에서 build된 프로젝트를 가져온다
## package 종속석 설치
COPY --from=builder /app/package*.json .
RUN npm install
## 배포파일 가져오기
COPY --from=builder /app/dist ./dist
## application 실행
CMD ["npm","run","start:prod"]